# Generated by Django 5.1.6 on 2025-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=100)),
                ('check_type', models.CharField(choices=[('borders', 'Мин/Макс'), ('exact_value', 'Точное значение (Float)'), ('string_value', 'Точное значение (String)'), ('day_count', 'Дней до сегодняшнего')], max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('exact_value', models.FloatField(blank=True, null=True)),
                ('measure_of_calculation', models.CharField(choices=[('None', 'Просто число'), ('GB', 'Gb')], default='None', max_length=50)),
                ('day_count', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, unique=True, verbose_name='Имя ПК')),
                ('mem', models.CharField(max_length=50, verbose_name='Объем памяти')),
                ('osver', models.CharField(max_length=100, verbose_name='Операционная система')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
